# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Catflap < Formula
  desc "Ephemeral capability gateway for AI agents: lend a machine, not a credential."
  homepage "https://github.com/juntaki/catflap"
  version "0.8.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/juntaki/catflap/releases/download/v0.8.0/catflap_0.8.0_darwin_arm64.tar.gz"
      sha256 "da10f64eba59ea492e2cb76d051e5ba749099f839fc45cb194732a4540dfeae8"

      define_method(:install) do
        bin.install "catflap"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/juntaki/catflap/releases/download/v0.8.0/catflap_0.8.0_linux_amd64.tar.gz"
      sha256 "e3e1ca692cef115868c51b82daca67b31cb37da1d2ae3807288645a90da19ab3"
      define_method(:install) do
        bin.install "catflap"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/juntaki/catflap/releases/download/v0.8.0/catflap_0.8.0_linux_arm64.tar.gz"
      sha256 "70f29d124bd2316b83fde8bf10fc10c9e83558875e0419ac523e32163c3d7b82"
      define_method(:install) do
        bin.install "catflap"
      end
    end
  end

  test do
    system "#{bin}/catflap", "version"
  end
end
